In [3]:
thislist =['foo', 'bar', 'baz','kuz','nex']
thislist[1:2]= ['Joko', 'Dada']
thislist

['foo', 'Joko', 'Dada', 'baz', 'kuz', 'nex']

In [10]:
def convert_f_to_c(f):
    c = float(f-32) *5 /9
    return
def convert_f_to_k(f):
    k = (float(f-32)*5/9)+273
    return


convert_f_to_c(100)
convert_f_to_k(100)


In [42]:
9Myname="Budi"
print(9Myname)

SyntaxError: invalid syntax (<ipython-input-42-0e44894f250c>, line 1)

In [20]:
thislist=["aku", "kamu","saya","dia", "anda"]
thislist.pop(2)
print(thislist)

['aku', 'kamu', 'dia', 'anda']


In [21]:
y=list(thislist)
print(thislist)

['aku', 'kamu', 'dia', 'anda']


In [23]:
y.append('Pesawat')
thislist= tuple(y)

In [33]:
thislist=["aku", "kamu","saya","dia", "anda"]
y=list(thislist)
print(thislist)
y.append('Pesawat')
print(thislist)
thislist= tuple(y)
print(thislist)

['aku', 'kamu', 'saya', 'dia', 'anda']
['aku', 'kamu', 'saya', 'dia', 'anda']
('aku', 'kamu', 'saya', 'dia', 'anda', 'Pesawat')


In [27]:
thislist=["aku", "kamu","saya","dia", "anda"]
y=list(thislist)
y.extend('Pesawat')
thislist= tuple(y)
print(thislist)

('aku', 'kamu', 'saya', 'dia', 'anda', 'P', 'e', 's', 'a', 'w', 'a', 't')


In [31]:
thislist=["aku", "kamu","saya","dia", "anda"]
thislist2=["sepeda", "mobil"]
thislist.append(thislist2)
print(thislist)

['aku', 'kamu', 'saya', 'dia', 'anda', ['sepeda', 'mobil']]


In [34]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

thisdict.pop("brand")
print(thisdict)

{'model': 'mustang', 'year': 1984}


In [36]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

thisdict("year") = 2018

SyntaxError: cannot assign to function call (<ipython-input-36-40723a49da49>, line 7)

In [62]:
thisdict="farand austen mahesa"

w = thisdict.split()
print(w)

if len(w) % 2:
    print(w + "#")

['farand', 'austen', 'mahesa']


TypeError: can only concatenate list (not "str") to list

In [69]:
i =1
while i < 6:
    print(i)
    if i == 3:
        break
    i+=1

1
2
3


In [76]:
i = 0
while i < 6:
    i+=1
    if i == 3:
        continue
    print(i)

1
2
4
5
6


In [86]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

x = thisdict.keys()
print(x)

dict_keys(['brand', 'model', 'year'])


In [94]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

x = thisdict.popitem()
print(x)

('year', 1984)


In [102]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

del thisdict["brand"]
print(thisdict)

{'model': 'mustang', 'year': 1984}


In [99]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

thisdict.clear()
print(thisdict)

{}


In [104]:
thisdict = {
    "brand" : "ford",
    "model" : ["mustang", "2"],
    "year" : 1984
}

for i in thisdict:
    print(thisdict[i])

ford
['mustang', '2']
1984


In [1]:
def test(n):
    if n in range(3,9):
        print("%s is in the range "%str(n))
    else:
        print("The number.")
test(5)

5 is in the range 


In [2]:
def near(n):
    return ((abs(abs(1000-n) <= 100) and (abs(2000-n)<=100)))
print(near(1000))
print(near(900))  

False
False


In [3]:
def convert(fahr,kelv):
    cels = fahr *1.8 +32.0
    cels2 = kelv-273,15
    return cels
print(convert(10,32))

50.0


In [4]:
def printV():
    l = list()
    for i in range(1,21):
            l.append(i**3)
    print(l)
                   
printV()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000]


In [5]:
nums1 = [1,2,3]
nums2 = [4,5,6]
print("Original list:")
print(nums1)
print(nums2)
result = map(lambda x,y : x+y, nums1, nums2)
print("\nResult: after adding two half")
print(list(result))

Original list:
[1, 2, 3]
[4, 5, 6]

Result: after adding two half
[5, 7, 9]


In [6]:
r = lambda a :a +15
print (r(10))
r=lambda x,y :x*y
print(r(12,4))

25
48


In [7]:
def smallest(list):
    min = list[ 0 ]
    for a in list:
        if a < min:
            min = a
    return min
print(smallest((1,2,-8,0)))

-8


In [8]:
def sum_list(items):
    sum_numbers = 0
    for x in items:
        sum_numbers += x
    return sum_numbers
print(sum_list((1,2,-8)))

-5


In [9]:
import os
#host_name=os.environ['HOSTNAME']
#print("HOSTNAME:",host_name)
python_path = os.environ.get('PYTHONPATH')
print("Python Path: ", python_path)

Python Path:  None


In [10]:
def is_vowel(char):
    all_vowels ='aiueo'
    return  char in all_vowels
print(is_vowel('c'))
print(is_vowel('e'))

False
True


In [2]:
def convert1(fahr):
    cels = fahr * 1.8 + 32.0
    return cels
print(convert1(32))

89.6


In [ ]:
import calendar

year1 = int(input("input the year: "))
month1 = int(input("input the month: "))
print(calendar.month(year1,month1))

In [10]:
def string_r(str1):
    rstr=''
    index = len(str1)
    while index >0:
        rstr +=str1[index-1]
        index = index - 1
    return rstr
print(string_r('1234abcd'))

dcba4321


In [11]:
def fahr_to_c(temp):
    return (temp -32) * (5/9)
print(fahr_to_c(72))

22.22222222222222


In [12]:
def convert(fahr,kelv):
    cels = fahr *1.8 +32.0
    cels2 = kelv-273,15
    return cels
print(convert(32,20))

89.6


In [13]:
def sum(numbers):
    total =0
    for x in numbers:
        total += x
    return total
print(sum((8,2,3,0,7)))

20


In [1]:
import numpy as np
array_example = np.array([[[0,2,3,0],[1,4,3,0], [2,3,4,5],[2,1,2,3],[2,1,2,3]],
                           [[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4],[2,1,2,3]]])

print(array_example)
array_example.shape

[[[0 2 3 0]
  [1 4 3 0]
  [2 3 4 5]
  [2 1 2 3]
  [2 1 2 3]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [2 1 2 3]]]


(2, 5, 4)

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])

print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [2]:
a = str(input("Masukkan definisi: " )).upper()

if a == "KAMUAPA":
    print("Anda terkoneksi")
    b = int(input("Masukkan angka: " ))
    r = int(input("Masukkan angka: " ))
    i = b*r
    print("Nilainya ", i)

Masukkan definisi: kamuapa
Anda terkoneksi
Masukkan angka: 23
Masukkan angka: 43
Nilainya  989


In [5]:
import numpy as np


In [6]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr)
print(arr[1,1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
2


In [7]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)
print(arr[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [8]:
array_tes = np.array([3,7,10,2], ndmin=4)
print(array_tes)
print("number of dimension :", array_tes.ndim)

[[[[ 3  7 10  2]]]]
number of dimension : 4


In [9]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[1,-1])

5


In [10]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[1:5:4])

[5]


In [11]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[-3:-1])

[1 2]


In [12]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[2::2])
print(arr[::3])

[6 1 3]
[4 7 3]


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:12,2:])

[[ 3  4  5]
 [ 8  9 10]]


In [14]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
arr = np.array(['Kenshin', 'Himura','Tono'])
print(arr.dtype)

<U7


In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:9, 1:4])

[[2 3 4]
 [7 8 9]]


In [17]:
arr =np.array(['a','2','3'], dtype='S')
print(arr.dtype)

|S1


In [18]:
a = 210
b = 30
if a >b: print(a)

210


In [19]:
a = 210
b = 30
print("A") if a > b else print("=") if a == b else print("b")

A


In [21]:
a = 210
b = 30
c = 500
if a >b and c > a:
    print("Both conditions true")

Both conditions true


In [1]:
i = 1
while i <6:
    print(i)
    if i == 3:
        break
    i += 1   
        
        

1
2
3


In [2]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)    

1
2
4
5
6


In [10]:
#SAMA AJA ATAS BAWAH

fruits = ["Apple", "Banana", "Kita"]
for x in fruits:
    print(x)
    if x == "banana":
        break
    print(x)        

Apple
Apple
Banana
Banana
Kita
Kita


In [11]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

for i in thisdict:
    print(thisdict[i])

ford
mustang
1984


In [18]:
thisdict = {
    "brand" : "ford",
    "model" : "mustang",
    "year" : 1984
}

x = thisdict.items()
print(len(x))

thisdict["year"] = 2000
print(x)

3
dict_items([('brand', 'ford'), ('model', 'mustang'), ('year', 2000)])
